name: build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake curl file libtool libuv1-dev libjson-c-dev libwebsockets-dev
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: View build
        run: pwd && ls && ls build/
      - uses: actions/upload-artifact@v4
        with:
          name: ttyd
          path: build/ttyd
      - name: List build
        run: pwd && ls
          